version: '2'
services:
  traefik:
    image: rawmind/alpine-traefik:1.7.9-0
    environment:
      TRAEFIK_ADMIN_ENABLE: 'true'
      TRAEFIK_CONSTRAINTS: '"tag==demo"'
      TRAEFIK_HTTP_PORT: '80'
      TRAEFIK_RANCHER_DOMAIN: lvh.me
      TRAEFIK_RANCHER_ENABLE: 'true'
      TRAEFIK_RANCHER_MODE: metadata
    volumes:
    - /etc/localtime:/etc/localtime:ro
    ports:
    - 80:80/tcp
    - 8080:8000/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
  pmorjan-demo:
    image: pmorjan/demo
    labels:
      traefik.frontend.rule: Host:demo.lvh.me
      traefik.backend.circuitbreaker.expression: NetworkErrorRatio() > 0.5
      traefik.enable: 'true'
      traefik.backend: pmorjan-demo
      traefik.tags: demo
      logforwarding: 'true'
      traefik.port: '8080'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
